sudo: false

branches:
  only: 
    - master
    - v2-master

language: node_js

notifications:
  email:
    recipients:
      - devcenter@docusign.com
    on_success: never
    on_failure: change

node_js:
  - "12"
  - "13"
  - "14"
  - "16"

cache:
  directories:
    - "node_modules"

after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"

